export const GUEST_TITLE = Object.freeze({
  MR: 'MR',
  MRS: 'MRS',
  MISS: 'MISS',
  CHIEF: 'CHIEF',
  ALHAJI: 'ALHAJI',
  ALHAJA: 'ALHAJA',
  PASTOR: 'PASTOR',
  REVD: 'REVD',
  DEACON: 'DEACON',
  DEACONNESS: 'DEACONNESS',
  HRM: 'HRM'
})

export const GUEST_TITLE_LABEL = Object.freeze({
  [GUEST_TITLE.MR]: 'Mr',
  [GUEST_TITLE.MRS]: 'Mrs',
  [GUEST_TITLE.MISS]: 'Miss',
  [GUEST_TITLE.CHIEF]: 'Chief',
  [GUEST_TITLE.ALHAJI]: 'Alhaji',
  [GUEST_TITLE.ALHAJA]: 'Alhaja',
  [GUEST_TITLE.PASTOR]: 'Pastor',
  [GUEST_TITLE.REVD]: 'Revd',
  [GUEST_TITLE.DEACON]: 'Deacon',
  [GUEST_TITLE.DEACONNESS]: 'Deaconness',
  [GUEST_TITLE.HRM]: 'HRM'
})

export const NEXT_OF_KIN_RELATIONSHIP = Object.freeze({
  PARENT: 'PARENT',
  FRIEND: 'FRIEND',
  CHILD: 'CHILD',
  SPOUSE: 'SPOUSE'
})

export const NEXT_OF_KIN_RELATIONSHIP_LABEL = Object.freeze({
  [NEXT_OF_KIN_RELATIONSHIP.PARENT]: 'Parent',
  [NEXT_OF_KIN_RELATIONSHIP.FRIEND]: 'Friend',
  [NEXT_OF_KIN_RELATIONSHIP.CHILD]: 'Child',
  [NEXT_OF_KIN_RELATIONSHIP.SPOUSE]: 'Spouse'
})
