export const STAFF_ROLES = Object.freeze({
  FRONT_DESK_OFFICER: 'FRONT_DESK_OFFICER',
  // ADMINISTRATOR: 'ADMINISTRATOR',
  // GYM_MANAGER: 'GYM_MANAGER',
  // GYM_STAFF: 'GYM_STAFF',
  // BAR_MANAGER: 'BAR_MANAGER',
  // BAR_STAFF: 'BAR_STAFF',
  // RESTAURANT_MANAGER: 'RESTAURANT_MANAGER',
  // RESTAURANT_STAFF: 'RESTAURANT_STAFF',
  BANQUET_MANAGER: 'BANQUET_MANAGER',
  BANQUET_STAFF: 'BANQUET_STAFF',
  // CAFE_MANAGER: 'CAFE_MANAGER',
  // CAFE_STAFF: 'CAFE_STAFF',
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  OWNER: 'OWNER'
})

export const STAFF_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE'
})

export const STAFF_ROLES_LABEL = Object.freeze({
  [STAFF_ROLES.FRONT_DESK_OFFICER]: 'Front desk officer',
  [STAFF_ROLES.ADMINISTRATOR]: 'Adminstrator',
  [STAFF_ROLES.GYM_MANAGER]: 'Gym manager',
  [STAFF_ROLES.GYM_STAFF]: 'Gym staff',
  [STAFF_ROLES.BAR_MANAGER]: 'Bar manager',
  [STAFF_ROLES.BAR_STAFF]: 'Bar staff',
  [STAFF_ROLES.RESTAURANT_MANAGER]: 'Restaurant manager',
  [STAFF_ROLES.RESTAURANT_STAFF]: 'Restaurant staff',
  [STAFF_ROLES.BANQUET_MANAGER]: 'Banquet manager',
  [STAFF_ROLES.BANQUET_STAFF]: 'Banquet staff',
  [STAFF_ROLES.CAFE_MANAGER]: 'Cafe manager',
  [STAFF_ROLES.CAFE_STAFF]: 'Cafe staff',
  [STAFF_ROLES.GENERAL_MANAGER]: 'General manager',
  [STAFF_ROLES.OWNER]: 'Owner'
})

export const STAFF_STATUS_LABEL = Object.freeze({
  [STAFF_STATUS.ACTIVE]: 'Active',
  [STAFF_STATUS.SUSPENDED]: 'Suspended',
  [STAFF_STATUS.PENDING]: 'Pending',
  [STAFF_STATUS.INACTIVE]: 'Inactive',
  [STAFF_STATUS.ON_LEAVE]: 'On leave'
})
