import { STAFF_ROLES } from './staff'

export const PAYMENT_METHOD = Object.freeze({
  POS: 'POS',
  CASH: 'CASH',
  ONLINE: 'ONLINE',
  BANK_TRANSFER: 'BANK_TRASFER'
})

export const CSV_TYPE = Object.freeze({
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  CUSTOMERS: 'CUSTOMERS'
})

export const PAYMENT_STATUS = Object.freeze({
  PAID: 'PAID',
  UNPAID: 'UNPAID'
})

export const GUEST_EXPENSES_TYPE = Object.freeze({
  [STAFF_ROLES.FRONT_DESK_OFFICER]: 'FRONTDESK',
  [STAFF_ROLES.BAR_STAFF]: 'BAR',
  [STAFF_ROLES.RESTAURANT_STAFF]: 'RESTAURANT'
})

export const TODOS_REMINDER_AT = Object.freeze({
  FIVE_MIN_BEFORE: '5MINBEFORE',
  FIFTEEN_MIN_BEFORE: '15MINBEFORE',
  THIRTY_MIN_BEFORE: '30MINBEFORE',
  ONE_HOUR_BEFORE: '1HOURBEFORE'
})

export const COMPANY_SIZE = Object.freeze({
  ONE_TO_FIVE: 'ONE_TO_FIVE',
  FIVE_TO_TEN: 'FIVE_TO_TEN',
  TEN_TO_TWENTY: 'TEN_TO_TWENTY',
  TWENTY_TO_FIFTY: 'TWENTY_TO_FIFTY',
  FIFTY_TO_HUNDRED: 'FIFTY_TO_HUNDRED',
  ONE_HUNDRED_PLUS: 'ONE_HUDRED_PLUS'
})

export const SCHEDULE_FREQUENCY = Object.freeze({
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
})

export const GUEST_SCHEDULE_RECIEVER = Object.freeze({
  CURRENT_IN_HOUSE_GUEST: 'CURRENT_IN_HOUSE_GUEST',
  GUEST_THIS_MONTH: 'GUEST_THIS_MONTH',
  GUEST_LAST_MONTH: 'GUEST_LAST_MONTH',
  GUEST_THIS_YEAR: 'GUEST_THIS_YEAR'
})

export const TEMPLATES_TYPE = Object.freeze({
  GUEST: 'GUEST',
  INVOICE: 'INVOICE',
  EVENT: 'EVENT',
  ESTIMATE: 'ESTIMATE'
})
