export const STAFF_ROLES = Object.freeze({
  FRONT_DESK_OFFICER: 'FRONT_DESK_OFFICER',
  ADMINISTRATOR: 'ADMINISTRATOR',
  GYM_MANAGER: 'GYM_MANAGER',
  GYM_STAFF: 'GYM_STAFF',
  BAR_MANAGER: 'BAR_MANAGER',
  BAR_STAFF: 'BAR_STAFF',
  RESTAURANT_MANAGER: 'RESTAURANT_MANAGER',
  RESTAURANT_STAFF: 'RESTAURANT_STAFF',
  BANQUET_MANAGER: 'BANQUET_MANAGER',
  BANQUET_STAFF: 'BANQUET_STAFF',
  CAFE_MANAGER: 'CAFE_MANAGER',
  CAFE_STAFF: 'CAFE_STAFF',
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  OWNER: 'OWNER'
})

export const STAFF_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE'
})
