const STAFF_ROLES = Object.freeze({
  FRONT_DESK_OFFICER: 'FRONT_DESK_OFFICER',
  ADMINISTRATOR: 'ADMINISTRATOR',
  GYM_MANAGER: 'GYM_MANAGER',
  GYM_STAFF: 'GYM_STAFF',
  BAR_MANAGER: 'BAR_MANAGER',
  BAR_STAFF: 'BAR_STAFF',
  RESTAURANT_MANAGER: 'RESTAURANT_MANAGER',
  RESTAURANT_STAFF: 'RESTAURANT_STAFF',
  BANQUET_MANAGER: 'BANQUET_MANAGER',
  BANQUET_STAFF: 'BANQUET_STAFF',
  CAFE_MANAGER: 'CAFE_MANAGER',
  CAFE_STAFF: 'CAFE_STAFF',
  MANAGER: 'MANAGER'
})

const STAFF_STATUS = Object.freeze({
  ON_LEAVE: 'ON_LEAVE',
  RESIGNED: 'RESIGNED',
  LEFT: 'LEFT'
})

export {
  STAFF_ROLES,
  STAFF_STATUS
}
