export const FETCH_BOOKING_LOADING = 'FETCH_BOOKING_LOADING'
export const FETCH_BOOKING_ERROR = 'FETCH_BOOKING_ERROR'
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS'

export const ADD_BOOKING = 'ADD_NEW_BOOKING'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'
export const DELETE_BOOKING = 'DELETE_BOOKING'
