export const FETCH_CHECKIN_LOADING = 'FETCH_CHECKIN_LOADING'
export const FETCH_CHECKIN_ERROR = 'FETCH_CHECKIN_ERROR'
export const FETCH_CHECKIN_SUCCESS = 'FETCH_CHECKIN_SUCCESS'

export const ADD_CHECKIN = 'ADD_NEW_CHECKIN'
export const UPDATE_CHECKIN = 'UPDATE_CHECKIN'
export const DELETE_CHECKIN = 'DELETE_CHECKIN'
