export const FETCH_HALL_LOADING = 'FETCH_HALL_LOADING'
export const FETCH_HALL_ERROR = 'FETCH_HALL_ERROR'
export const FETCH_HALL_SUCCESS = 'FETCH_HALL_SUCCESS'

export const ADD_HALL = 'ADD_NEW_HALL'
export const UPDATE_HALL = 'UPDATE_HALL'
export const DELETE_HALL = 'DELETE_HALL'
