export const FETCH_ROOMTYPE_LOADING = 'FETCH_ROOMTYPE_LOADING'
export const FETCH_ROOMTYPE_ERROR = 'FETCH_ROOMTYPE_ERROR'
export const FETCH_ROOMTYPE_SUCCESS = 'FETCH_ROOMTYPE_SUCCESS'

export const ADD_NEW_ROOMTYPE = 'ADD_NEW_ROOMTYPE'
export const UPDATE_ROOMTYPE_DETAILS = 'UPDATE_ROOMTYPE_DETAILS'
export const DELETE_ROOMTYPE = 'DELETE_ROOMTYPE'
