export const FETCH_STAFF_LOADING = 'FETCH_STAFF_LOADING'
export const FETCH_STAFF_ERROR = 'FETCH_STAFF_ERROR'
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'

export const FETCH_CURRENT_STAFF_LOADING = 'FETCH_CURRENT_STAFF_LOADING'
export const FETCH_CURRENT_STAFF_ERROR = 'FETCH_CURRENT_STAFF_ERROR'
export const FETCH_CURRENT_STAFF_SUCCESS = 'FETCH_CURRENT_STAFF_SUCCESS'
export const LOGOUT = 'LOGOUT'

export const ADD_NEW_STAFF = 'ADD_NEW_STAFF'
export const UPDATE_STAFF_DETAILS = 'UPDATE_STAFF_DETAILS'
export const DELETE_STAFF = 'DELETE_STAFF'
